// Generated by https://quicktype.io

export interface Profesores {
  id: number;
  usuario: string;
  contrasena: string;
  email: string;
  nombre: string;
  idCuenta: number;
  createdAt: string;
  updatedAt: string;
}
