// Generated by https://quicktype.io

export interface Alumnos {
  id: number;
  primer_Nombre: string;
  segundo_Nombre: string;
  primer_Apellido: string;
  segundo_Apellido: string;
  identificacion: string;
  id_profesor: number;
  createdAt: string;
  updatedAt: string;
}
